services:
  frontend:
    image: ghcr.io/jangiese/marrygram-frontend:development
    container_name: marrygram-frontend
    restart: always
    env_file:
      - stack.env
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  backend:
    image: ghcr.io/jangiese/marrygram-backend:development
    container_name: marrygram-backend
    restart: always
    env_file:
      - stack.env
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      media-compressor:
        condition: service_healthy
    extra_hosts:
      - "minio.jpgiese.com:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health/liveness"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  media-compressor:
    image: ghcr.io/jangiese/marrygram-media-compressor:latest
    container_name: marrygram-media-compressor
    restart: always
    env_file:
      - stack.env
    depends_on:
      minio:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    extra_hosts:
      - "minio.jpgiese.com:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  db:
    image: postgres:17
    container_name: marrygram-db
    restart: always
    ports: # remove for production
      - "6432:5432"
    env_file:
      - stack.env
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init_db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio
    container_name: marrygram-storage
    command: server /data --console-address ":9001"
    restart: always
    env_file:
      - stack.env
    volumes:
      - minio-data:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: marrygram-rabbitmq
    restart: always
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db-data:
  minio-data:

networks:
  default:
    name: nginx
    external: true
