services:
  frontend:
    image: ghcr.io/jangiese/marrygram-frontend:${FRONTEND_TAG}
    ports:
      - "4300:80"

  backend:
    image: ghcr.io/jangiese/marrygram-backend:${BACKEND_TAG}
    ports:
      - "8080:8080"

  media-compressor:
    image: ghcr.io/jangiese/marrygram-media-compressor:${MEDIA_COMPRESSOR_TAG}

  db:
    ports:
      - "5432:5432"
    volumes:
      - db-data-test:/var/lib/postgresql/data

  minio:
    ports:
      - "9000:9000"
    volumes:
      - minio-data-test:/data

  rabbitmq:
    ports:
      - "5672:5672"

volumes:
  db-data-test:
  minio-data-test: