

-- DROP SEQUENCE address_line_id_seq;

CREATE SEQUENCE address_line_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE event_location_id_seq;

CREATE SEQUENCE event_location_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE guest_id_seq;

CREATE SEQUENCE guest_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE like_id_seq;

CREATE SEQUENCE like_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE menu_item_id_seq;

CREATE SEQUENCE menu_item_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE schedule_item_id_seq;

CREATE SEQUENCE schedule_item_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE task_id_seq;

CREATE SEQUENCE task_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE task_template_id_seq;

CREATE SEQUENCE task_template_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE upload_id_seq;

CREATE SEQUENCE upload_id_seq
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    START 1
	CACHE 1
	NO CYCLE;-- core.event_location definition

-- Drop table

-- DROP TABLE event_location;

CREATE TABLE event_location (
                                id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                routes_address varchar(255) NULL,
                                unsafe_map_url varchar(32600) NULL,
                                CONSTRAINT event_location_pkey PRIMARY KEY (id)
);


-- core.flyway_schema_history definition

-- Drop table

-- DROP TABLE flyway_schema_history;

CREATE TABLE flyway_schema_history (
                                       installed_rank int4 NOT NULL,
                                       "version" varchar(50) NULL,
                                       description varchar(200) NOT NULL,
                                       "type" varchar(20) NOT NULL,
                                       script varchar(1000) NOT NULL,
                                       checksum int4 NULL,
                                       installed_by varchar(100) NOT NULL,
                                       installed_on timestamp DEFAULT now() NOT NULL,
                                       execution_time int4 NOT NULL,
                                       success bool NOT NULL,
                                       CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank)
);
CREATE INDEX flyway_schema_history_s_idx ON core.flyway_schema_history USING btree (success);


-- core.guest definition

-- Drop table

-- DROP TABLE guest;

CREATE TABLE guest (
                       id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                       active bool NOT NULL,
                       created_at timestamp(6) NULL,
                       email varchar(255) NULL,
                       "name" varchar(255) NULL,
                       qr_code_token varchar(255) NULL,
                       is_admin bool DEFAULT false NOT NULL,
                       last_login_at timestamp(6) NULL,
                       profile_image_path varchar(255) NULL,
                       rsvp bool NULL,
                       profile_image_compressed_path varchar(255) NULL,
                       CONSTRAINT guest_pkey PRIMARY KEY (id)
);


-- core.menu_item definition

-- Drop table

-- DROP TABLE menu_item;

CREATE TABLE menu_item (
                           id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                           category int2 NULL,
                           description varchar(255) NULL,
                           "name" varchar(255) NULL,
                           order_index int4 NOT NULL,
                           CONSTRAINT menu_item_category_check CHECK (((category >= 0) AND (category <= 3))),
                           CONSTRAINT menu_item_pkey PRIMARY KEY (id)
);


-- core.schedule_item definition

-- Drop table

-- DROP TABLE schedule_item;

CREATE TABLE schedule_item (
                               id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                               "name" varchar(255) NULL,
                               order_index int4 NOT NULL,
                               "time" varchar(255) NULL,
                               CONSTRAINT schedule_item_pkey PRIMARY KEY (id)
);


-- core.task_template definition

-- Drop table

-- DROP TABLE task_template;

CREATE TABLE task_template (
                               id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                               active bool NOT NULL,
                               description varchar(255) NULL,
                               title varchar(255) NULL,
                               CONSTRAINT task_template_pkey PRIMARY KEY (id)
);


-- core.address_line definition

-- Drop table

-- DROP TABLE address_line;

CREATE TABLE address_line (
                              id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                              order_index int4 NOT NULL,
                              "text" varchar(255) NULL,
                              event_location_id int8 NOT NULL,
                              CONSTRAINT address_line_pkey PRIMARY KEY (id),
                              CONSTRAINT fkk15np01t8axmddsimqk7y02eu FOREIGN KEY (event_location_id) REFERENCES event_location(id)
);


-- core."like" definition

-- Drop table

-- DROP TABLE "like";

CREATE TABLE "like" (
                        id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                        created_at timestamp(6) NULL,
                        upload_id int8 NULL,
                        guest_id int8 NULL,
                        CONSTRAINT like_pkey PRIMARY KEY (id),
                        CONSTRAINT fk9tu8d8c1ots5fjtfpm02f0dka FOREIGN KEY (guest_id) REFERENCES guest(id)
);


-- core.upload definition

-- Drop table

-- DROP TABLE upload;

CREATE TABLE upload (
                        id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                        created_at timestamp(6) NULL,
                        filename varchar(255) NULL,
                        filename_compressed varchar(255) NULL,
                        title varchar(255) NULL,
                        "type" varchar(255) NULL,
                        guest_id int8 NULL,
                        CONSTRAINT upload_pkey PRIMARY KEY (id),
                        CONSTRAINT fk2p52f8nev0sr91utx2icgkh8y FOREIGN KEY (guest_id) REFERENCES guest(id)
);


-- core.task definition

-- Drop table

-- DROP TABLE task;

CREATE TABLE task (
                      id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                      completed bool NOT NULL,
                      guest_id int8 NOT NULL,
                      task_template_id int8 NOT NULL,
                      upload_id int8 NULL,
                      CONSTRAINT task_pkey PRIMARY KEY (id),
                      CONSTRAINT uk7c3u7aschuutupw9khm3cyixs UNIQUE (upload_id),
                      CONSTRAINT fk247u3ij3v4rcr6wx8gefr1q96 FOREIGN KEY (task_template_id) REFERENCES task_template(id),
                      CONSTRAINT fk3ksnf8ocq6lljx0eok0sx515j FOREIGN KEY (upload_id) REFERENCES upload(id),
                      CONSTRAINT fk774rin5wgt4h16lb5vw3jxugi FOREIGN KEY (guest_id) REFERENCES guest(id)
);