-- Create schema and set search path
CREATE SCHEMA core;
ALTER
DATABASE :appDbName SET search_path TO core;

CREATE TABLE core.guest
(
    id            int8 GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    active        bool                                                                                                                     NOT NULL,
    is_admin      bool,
    created_at    timestamp(6) NULL,
    email         varchar(255) NULL,
    "name"        varchar(255) NULL,
    qr_code_token varchar(255) NULL,
    CONSTRAINT guest_pkey PRIMARY KEY (id)
);
