name: 'Run Cypress Tests'
description: 'Runs Cypress tests and uploads results'
inputs:
  working-directory:
    required: false
    description: 'The working directory to run Cypress tests in'
    default: '.'
  artifact-retention-days:
    default: '7'
    required: false
    description: 'Days to retain test artifacts'
  upload-artifacts:
    default: 'true'
    required: false
    description: 'Whether to upload test artifacts'
  rabbitmq-mgmt-url:
    default: 'http://localhost:15672'
    required: false
    description: 'RabbitMQ Management URL for Cypress'
  minio-url:
    default: 'http://localhost:9000'
    required: false
    description: 'MinIO URL for Cypress'
  api-url:
    default: 'http://localhost:8080'
    required: false
    description: 'API URL for Cypress'
  base-url:
    default: 'http://localhost:4200'
    required: false
    description: 'Cypress base URL'

runs:
  using: 'composite'
  steps:
    - name: Run Cypress tests
      shell: bash
      run: npm run test
      working-directory: ${{ inputs.working-directory }}
      env:
        CYPRESS_RABBITMQ_MGMT_URL: ${{ inputs.rabbitmq-mgmt-url }}
        CYPRESS_MINIO_URL: ${{ inputs.minio-url }}
        CYPRESS_API_URL: ${{ inputs.api-url }}
        CYPRESS_BASE_URL: ${{ inputs.base-url }}

    - name: Upload test results
      if: always() && inputs.upload-artifacts == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: cypress-results
        path: |
          ${{ inputs.working-directory }}/cypress/screenshots
          ${{ inputs.working-directory }}/cypress/videos
        retention-days: ${{ inputs.artifact-retention-days }}

    - name: Upload test report
      if: always() && inputs.upload-artifacts == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: ${{ inputs.working-directory }}/cypress/results
        retention-days: ${{ inputs.artifact-retention-days }}
