name: Default docker tags

outputs:
  frontend:
    value: latest
  backend:
    value: latest
  media:
    value: latest

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        echo "frontend=latest" >> $GITHUB_OUTPUT
        echo "backend=latest" >> $GITHUB_OUTPUT
        echo "media=latest" >> $GITHUB_OUTPUT
