name: Integration test

on:
  pull_request:
    branches:
      - main
permissions:
  contents: read
  pull-requests: read
  issues: write

jobs:
  integration-test:
    runs-on: ubuntu-latest

    steps:
      - name: Run integration tests
        uses: JanGiese/marrygram-docker/.github/actions/pr-trigger-integration-test@feature/integration-tests
        with:
          password: ${{ secrets.PAT_TOKEN }}
          issue_number: ${{ github.event.pull_request.number }}
          repo: ${{ github.repository }}
          repo_owner: ${{ github.repository_owner }}