name: Integration Tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main, feture/*, feature/*]
  workflow_dispatch:

jobs:
  integration-tests:
    uses: JanGiese/marrygram-docker/.github/workflows/integration-test.yml@feture/restructure_workflows_and_actions
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
