name: Resolve docker tags

inputs:
  token:
    required: true
  issue_number:
    required: true
  repo:
    required: true
  repo_owner:
    required: true

outputs:
  frontend:
    value: ${{ steps.tags.outputs.frontend }}
  backend:
    value: ${{ steps.tags.outputs.backend }}
  media:
    value: ${{ steps.tags.outputs.media }}
  comment_id:
    value: ${{ steps.tags.outputs.comment_id }}

runs:
  using: composite
  steps:
    - id: tags
      uses: actions/github-script@v7
      env:
        REPO_OWNER: ${{ github.repository_owner }}
        REPO: ${{ github.repository }}
        ISSUE_NUMBER: ${{ github.event.pull_request.number }}
      with:
        github-token: ${{ inputs.token }}
        script: |
          const owner = process.env.REPO_OWNER;
          const repo = process.env.REPO;
          const issue_number = Number(process.env.ISSUE_NUMBER);

          const marker = '<!-- integration-test -->';

          const defaultTags = {
            frontend: 'latest',
            backend: 'latest',
            media: 'latest',
          };

          if (repo === 'marrygram-backend') defaultTags.backend = 'development';
          if (repo === 'marrygram-frontend') defaultTags.frontend = 'development';
          if (repo === 'marrygram-media-compressor') defaultTags.media = 'development';

          const { data: comments } = await github.rest.issues.listComments({
            owner,
            repo,
            issue_number,
          });

          let comment = comments.find(c => c.body?.includes(marker));

          if (!comment) {
            const body = `
            ${marker}
            ### 🧪 Integration tests

            **Docker images**
            - marrygram-frontend: \`${defaultTags.frontend}\`
            - marrygram-backend: \`${defaultTags.backend}\`
            - marrygram-media-compressor: \`${defaultTags.media}\`

            **Status**
            ⏳ Waiting for results...
            `;

            comment = (
              await github.rest.issues.createComment({
                owner,
                repo,
                issue_number,
                body,
              })
            ).data;
          }

          const extract = (name) =>
            comment.body.match(new RegExp(`${name}:\\s*\\\`([^\\\`]+)`))?.[1];

          core.setOutput('comment_id', comment.id);
          core.setOutput('frontend', extract('marrygram-frontend') ?? defaultTags.frontend);
          core.setOutput('backend', extract('marrygram-backend') ?? defaultTags.backend);
          core.setOutput('media', extract('marrygram-media-compressor') ?? defaultTags.media);

